version: "2"
services:
    www:
        build: .
        container_name: flarum
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
            - ./apache-config:/etc/apache2/sites-enabled/
        links:
            - db
        networks:
            - default
    db:
        image: mysql
        container_name: mysql
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: flarumDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
volumes:
    persistent:
